# Generated by Django 5.1.3 on 2024-11-26 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0004_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gl',
            field=models.CharField(blank=True, choices=[('SHEMA NOIR', 'SHEMA NOIR'), ('SHEMABLEU', 'SHEMA BLEU')], max_length=15, null=True, verbose_name='Groupe local'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='camp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camps.camp'),
        ),
    ]
