# Generated by Django 5.1.3 on 2024-11-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0005_camp_alter_customuser_gl_alter_customuser_camp'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='Budget',
            field=models.FileField(blank=True, null=True, upload_to='Budget/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='CR_prospe',
            field=models.FileField(blank=True, null=True, upload_to='CR_prospe/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='GL1',
            field=models.CharField(blank=True, choices=[('SHEMA NOIR', 'SHEMA NOIR'), ('SHEMABLEU', 'SHEMA BLEU')], max_length=15, null=True, verbose_name='Groupe local 1'),
        ),
        migrations.AddField(
            model_name='camp',
            name='GL2',
            field=models.CharField(blank=True, choices=[('SHEMA NOIR', 'SHEMA NOIR'), ('SHEMABLEU', 'SHEMA BLEU')], max_length=15, null=True, verbose_name='Groupe local 2'),
        ),
        migrations.AddField(
            model_name='camp',
            name='GL3',
            field=models.CharField(blank=True, choices=[('SHEMA NOIR', 'SHEMA NOIR'), ('SHEMABLEU', 'SHEMA BLEU')], max_length=15, null=True, verbose_name='Groupe local 3'),
        ),
        migrations.AddField(
            model_name='camp',
            name='GL4',
            field=models.CharField(blank=True, choices=[('SHEMA NOIR', 'SHEMA NOIR'), ('SHEMABLEU', 'SHEMA BLEU')], max_length=15, null=True, verbose_name='Groupe local 4'),
        ),
        migrations.AddField(
            model_name='camp',
            name='adresse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='branche',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='chemins_explo',
            field=models.FileField(blank=True, null=True, upload_to='chemins_explo/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='contrat_location',
            field=models.FileField(blank=True, null=True, upload_to='contrat_location/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='fiche_sncf',
            field=models.FileField(blank=True, null=True, upload_to='fiche_sncf/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='fil_bleu',
            field=models.FileField(blank=True, null=True, upload_to='fil_bleu/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='fil_rouge',
            field=models.FileField(blank=True, null=True, upload_to='fil_rouge/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='fil_vert',
            field=models.FileField(blank=True, null=True, upload_to='fil_vert/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_assurance',
            field=models.FileField(blank=True, null=True, upload_to='grille_assurance/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_ddcs',
            field=models.FileField(blank=True, null=True, upload_to='grille_ddcs/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_intendance',
            field=models.FileField(blank=True, null=True, upload_to='grille_intendance/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='nomcdc1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom du chef de camp 1'),
        ),
        migrations.AddField(
            model_name='camp',
            name='nomcdc2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom du chef de camp 2'),
        ),
        migrations.AddField(
            model_name='camp',
            name='prenomcdc1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Prénom du chef de camp 1'),
        ),
        migrations.AddField(
            model_name='camp',
            name='prenomcdc2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Prénom du chef de camp 2'),
        ),
        migrations.AddField(
            model_name='camp',
            name='procuration_banque',
            field=models.FileField(blank=True, null=True, upload_to='procuration_banque/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='recepisse',
            field=models.FileField(blank=True, null=True, upload_to='recepisse/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='staff1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Staff 1'),
        ),
        migrations.AddField(
            model_name='camp',
            name='staff2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Staff 2'),
        ),
        migrations.AddField(
            model_name='camp',
            name='staff3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Staff 3'),
        ),
    ]
