# Generated by Django 5.1.3 on 2024-12-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0006_camp_budget_camp_cr_prospe_camp_gl1_camp_gl2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='Budget',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/Budget/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='CR_prospe',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/CR_prospe/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='GL1',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Bar Cokhba', 'Bar Cokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrénoy', 'Dufrénoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-Bois', 'Pavillons-sous-Bois'), ('Saint Brice', 'Saint Brice'), ('Ségur', 'Ségur'), ('Shema Israël Bleu', 'Shema Israël Bleu'), ('Shema Israël Noir', 'Shema Israël Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona')], max_length=30, null=True, verbose_name='Groupe local 1'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='GL2',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Bar Cokhba', 'Bar Cokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrénoy', 'Dufrénoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-Bois', 'Pavillons-sous-Bois'), ('Saint Brice', 'Saint Brice'), ('Ségur', 'Ségur'), ('Shema Israël Bleu', 'Shema Israël Bleu'), ('Shema Israël Noir', 'Shema Israël Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona')], max_length=30, null=True, verbose_name='Groupe local 2'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='GL3',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Bar Cokhba', 'Bar Cokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrénoy', 'Dufrénoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-Bois', 'Pavillons-sous-Bois'), ('Saint Brice', 'Saint Brice'), ('Ségur', 'Ségur'), ('Shema Israël Bleu', 'Shema Israël Bleu'), ('Shema Israël Noir', 'Shema Israël Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona')], max_length=30, null=True, verbose_name='Groupe local 3'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='GL4',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Bar Cokhba', 'Bar Cokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrénoy', 'Dufrénoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-Bois', 'Pavillons-sous-Bois'), ('Saint Brice', 'Saint Brice'), ('Ségur', 'Ségur'), ('Shema Israël Bleu', 'Shema Israël Bleu'), ('Shema Israël Noir', 'Shema Israël Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona')], max_length=30, null=True, verbose_name='Groupe local 4'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='chemins_explo',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/chemins_explo/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='contrat_location',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/contrat_location/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='fiche_sncf',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/fiche_sncf/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='fil_bleu',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/fil_bleu/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='fil_rouge',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/fil_rouge/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='fil_vert',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/fil_vert/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='grille_assurance',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/grille_assurance/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='grille_ddcs',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/grille_ddcs/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='grille_intendance',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/grille_intendance/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='numero',
            field=models.CharField(blank=True, choices=[('BC 1', 'BC 1'), ('BC 2', 'BC 2'), ('BC 3', 'BC 3'), ('BC 4', 'BC 4'), ('BC 5', 'BC 5'), ('BC 6', 'BC 6'), ('BC 7', 'BC 7'), ('BC 8', 'BC 8'), ('BC 9', 'BC 9'), ('BC 10', 'BC 10'), ('BC 11', 'BC 11'), ('BC 12', 'BC 12'), ('BC 13', 'BC 13'), ('BC 14', 'BC 14'), ('BC 15', 'BC 15'), ('BC 16', 'BC 16'), ('BC 17', 'BC 17'), ('BC 18', 'BC 18'), ('BC 19', 'BC 19'), ('BC 20', 'BC 20'), ('BC 21', 'BC 21'), ('BC 22', 'BC 22'), ('BC 23', 'BC 23'), ('BC 24', 'BC 24'), ('BC 25', 'BC 25'), ('BM 1', 'BM 1'), ('BM 2', 'BM 2'), ('BM 3', 'BM 3'), ('BM 4', 'BM 4'), ('BM 5', 'BM 5'), ('BM 6', 'BM 6'), ('BM 7', 'BM 7'), ('BM 8', 'BM 8'), ('BM 9', 'BM 9'), ('BM 10', 'BM 10'), ('BM 11', 'BM 11'), ('BM 12', 'BM 12'), ('BM 13', 'BM 13'), ('BM 14', 'BM 14'), ('BM 15', 'BM 15'), ('BM 16', 'BM 16'), ('BM 17', 'BM 17'), ('BM 18', 'BM 18'), ('BM 19', 'BM 19'), ('BM 20', 'BM 20'), ('BM 21', 'BM 21'), ('BM 22', 'BM 22'), ('BM 23', 'BM 23'), ('BM 24', 'BM 24'), ('BM 25', 'BM 25'), ('BP 1', 'BP 1'), ('BP 2', 'BP 2'), ('BP 3', 'BP 3'), ('BP 4', 'BP 4'), ('BP 5', 'BP 5'), ('BP 6', 'BP 6'), ('BP 7', 'BP 7'), ('BP 8', 'BP 8'), ('BP 9', 'BP 9'), ('BP 10', 'BP 10')], max_length=30, null=True, verbose_name='Numéro du camp'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='procuration_banque',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/procuration_banque/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='recepisse',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/recepisse/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gl',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Bar Cokhba', 'Bar Cokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrénoy', 'Dufrénoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-Bois', 'Pavillons-sous-Bois'), ('Saint Brice', 'Saint Brice'), ('Ségur', 'Ségur'), ('Shema Israël Bleu', 'Shema Israël Bleu'), ('Shema Israël Noir', 'Shema Israël Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona')], max_length=30, null=True, verbose_name='Groupe local'),
        ),
    ]
