# Generated by Django 5.1.4 on 2025-01-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0008_camp_budget_etat_camp_cr_prospe_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='Budget_commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire du budget'),
        ),
        migrations.AddField(
            model_name='camp',
            name='CR_prospe_commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire du CR prospection'),
        ),
        migrations.AddField(
            model_name='camp',
            name='chemins_explo_commentaire',
            field=models.TextField(blank=True, null=True, verbose_name="Commentaire des chemins d'exploitation"),
        ),
        migrations.AddField(
            model_name='camp',
            name='contrat_location_commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire du contrat de location'),
        ),
        migrations.AddField(
            model_name='camp',
            name='fiche_sncf_commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire de la fiche SNCF'),
        ),
        migrations.AddField(
            model_name='camp',
            name='fil_bleu_commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire du fil bleu'),
        ),
        migrations.AddField(
            model_name='camp',
            name='fil_rouge_commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire du fil rouge'),
        ),
        migrations.AddField(
            model_name='camp',
            name='fil_vert_commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire du fil vert'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_assurance_commentaire',
            field=models.TextField(blank=True, null=True, verbose_name="Commentaire de la grille d'assurance"),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_ddcs_commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire de la grille DDCS'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_intendance_commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire de la grille intendance'),
        ),
        migrations.AddField(
            model_name='camp',
            name='procuration_banque_commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire de la procuration bancaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='recepisse_commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire du récépissé'),
        ),
    ]
