# Generated by Django 5.1.4 on 2025-01-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0010_alter_camp_budget_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='grille_camp',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/grille_camp/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_camp_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de la grille camp'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_camp_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu')], default='Non rendu', max_length=50, null=True, verbose_name='État de la grille camp'),
        ),
    ]
