# Generated by Django 5.1.4 on 2025-01-11 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0011_camp_grille_camp_camp_grille_camp_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='camps.camp'),
        ),
    ]
