# Generated by Django 5.1.4 on 2025-01-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0014_camp_gl5_alter_camp_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail'),
        ),
    ]
