# Generated by Django 5.1.4 on 2025-01-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0015_camp_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='Budget_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite du budget'),
        ),
        migrations.AddField(
            model_name='camp',
            name='CR_prospe_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite du CR prospection'),
        ),
        migrations.AddField(
            model_name='camp',
            name='chemins_explo_deadline',
            field=models.DateField(blank=True, null=True, verbose_name="Date limite des chemins d'exploitation"),
        ),
        migrations.AddField(
            model_name='camp',
            name='contrat_location_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite du contrat de location'),
        ),
        migrations.AddField(
            model_name='camp',
            name='fiche_sncf_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite de la fiche SNCF'),
        ),
        migrations.AddField(
            model_name='camp',
            name='fil_bleu_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite du fil bleu'),
        ),
        migrations.AddField(
            model_name='camp',
            name='fil_rouge_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite du fil rouge'),
        ),
        migrations.AddField(
            model_name='camp',
            name='fil_vert_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite du fil vert'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_assurance_deadline',
            field=models.DateField(blank=True, null=True, verbose_name="Date limite de la grille d'assurance"),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_camp_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite de la grille camp'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_ddcs_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite de la grille DDCS'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_intendance_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite de la grille intendance'),
        ),
        migrations.AddField(
            model_name='camp',
            name='procuration_banque_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite de la procuration bancaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='recepisse_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite du récépissé'),
        ),
    ]
