# Generated by Django 4.2.16 on 2025-01-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0016_camp_budget_deadline_camp_cr_prospe_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='animateurs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Nombre d'animateurs"),
        ),
        migrations.AddField(
            model_name='camp',
            name='date_JN',
            field=models.DateField(blank=True, null=True, verbose_name='Date des JN'),
        ),
        migrations.AddField(
            model_name='camp',
            name='enfants',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Nombre d'enfants"),
        ),
    ]
