# Generated by Django 4.2.16 on 2025-01-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0017_camp_animateurs_camp_date_jn_camp_enfants'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='demande_prospe',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/demande_prospe/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='demande_prospe_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='demande_prospe_deadline',
            field=models.CharField(blank=True, default='30 Janvier', max_length=50, null=True, verbose_name='Date limite demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='demande_prospe_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu')], default='Non rendu', max_length=50, null=True, verbose_name='État de la demande de prospe'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='contrat_location_deadline',
            field=models.CharField(blank=True, default='28 fevrier', max_length=50, null=True, verbose_name='Date limite du contrat de location'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='numero',
            field=models.CharField(blank=True, choices=[('BB 1', 'BB 1'), ('BB 2', 'BB 2'), ('BB 3', 'BB 3'), ('BB 4', 'BB 4'), ('BB 5', 'BB 5'), ('BC 1', 'BC 1'), ('BC 2', 'BC 2'), ('BC 3', 'BC 3'), ('BC 4', 'BC 4'), ('BC 5', 'BC 5'), ('BC 6', 'BC 6'), ('BC 7', 'BC 7'), ('BC 8', 'BC 8'), ('BC 9', 'BC 9'), ('BC 10', 'BC 10'), ('BC 11', 'BC 11'), ('BC 12', 'BC 12'), ('BC 13', 'BC 13'), ('BC 14', 'BC 14'), ('BC 15', 'BC 15'), ('BC 16', 'BC 16'), ('BC 17', 'BC 17'), ('BM 1', 'BM 1'), ('BM 2', 'BM 2'), ('BM 3', 'BM 3'), ('BM 4', 'BM 4'), ('BM 5', 'BM 5'), ('BM 6', 'BM 6'), ('BM 7', 'BM 7'), ('BM 8', 'BM 8'), ('BM 9', 'BM 9'), ('BM 10', 'BM 10'), ('BM 11', 'BM 11'), ('BM 12', 'BM 12'), ('BM 13', 'BM 13'), ('BM 14', 'BM 14'), ('BM 15', 'BM 15'), ('BM 16', 'BM 16'), ('BM 17', 'BM 17'), ('BM 18', 'BM 18'), ('BM 19', 'BM 19'), ('BM 20', 'BM 20'), ('BM 21', 'BM 21'), ('BM 22', 'BM 22'), ('BM 23', 'BM 23'), ('BM 24', 'BM 24'), ('BP 1', 'BP 1'), ('BP 2', 'BP 2'), ('BP 3', 'BP 3'), ('BP 4', 'BP 4'), ('BP 5', 'BP 5'), ('BP 6', 'BP 6'), ('BP 7', 'BP 7'), ('BP 8', 'BP 8'), ('BP 9', 'BP 9'), ('BP 10', 'BP 10'), ('BP 11', 'BP 11')], max_length=30, null=True, unique=True, verbose_name='Numéro du camp'),
        ),
    ]
