# Generated by Django 4.2.16 on 2025-02-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0018_camp_demande_prospe_camp_demande_prospe_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='BP',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Budget previsionnel'),
        ),
        migrations.AddField(
            model_name='camp',
            name='BP_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='BP_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du BP'),
        ),
        migrations.AddField(
            model_name='camp',
            name='GI',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Budget previsionnel'),
        ),
        migrations.AddField(
            model_name='camp',
            name='GI_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='GI_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du BP'),
        ),
        migrations.AddField(
            model_name='camp',
            name='PPP',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Budget previsionnel'),
        ),
        migrations.AddField(
            model_name='camp',
            name='PPP_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='PPP_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du BP'),
        ),
        migrations.AddField(
            model_name='camp',
            name='PPPc',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Budget previsionnel'),
        ),
        migrations.AddField(
            model_name='camp',
            name='PPPc_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='PPPc_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du BP'),
        ),
        migrations.AddField(
            model_name='camp',
            name='PPTPV',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Budget previsionnel'),
        ),
        migrations.AddField(
            model_name='camp',
            name='PPTPV_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='PPTPV_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du BP'),
        ),
        migrations.AddField(
            model_name='camp',
            name='V1GC',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Budget previsionnel'),
        ),
        migrations.AddField(
            model_name='camp',
            name='V1GC_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='V1GC_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du BP'),
        ),
        migrations.AddField(
            model_name='camp',
            name='V2GC',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Budget previsionnel'),
        ),
        migrations.AddField(
            model_name='camp',
            name='V2GC_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='V2GC_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du BP'),
        ),
        migrations.AddField(
            model_name='camp',
            name='VFGC',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Budget previsionnel'),
        ),
        migrations.AddField(
            model_name='camp',
            name='VFGC_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='VFGC_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du BP'),
        ),
        migrations.AddField(
            model_name='camp',
            name='casting',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Budget previsionnel'),
        ),
        migrations.AddField(
            model_name='camp',
            name='casting_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='casting_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du BP'),
        ),
        migrations.AddField(
            model_name='camp',
            name='devisbillet',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Budget previsionnel'),
        ),
        migrations.AddField(
            model_name='camp',
            name='devisbillet_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='devisbillet_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du BP'),
        ),
        migrations.AddField(
            model_name='camp',
            name='devislogement',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Budget previsionnel'),
        ),
        migrations.AddField(
            model_name='camp',
            name='devislogement_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='devislogement_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du BP'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='Budget_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du budget'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='CR_prospe_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du CR prospection'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='chemins_explo_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name="État des chemins d'exploitation"),
        ),
        migrations.AlterField(
            model_name='camp',
            name='contrat_location_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du contrat de location'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='demande_prospe_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État de la demande de prospe'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='fiche_sncf_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État de la fiche SNCF'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='fil_bleu_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du fil bleu'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='fil_rouge_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du fil rouge'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='fil_vert_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du fil vert'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='grille_assurance_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name="État de la grille d'assurance"),
        ),
        migrations.AlterField(
            model_name='camp',
            name='grille_camp_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État de la grille camp'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='grille_ddcs_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État de la grille DDCS'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='grille_intendance_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État de la grille intendance'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='procuration_banque_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État de la procuration bancaire'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='recepisse_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du récépissé'),
        ),
    ]
