# Generated by Django 4.2.16 on 2025-02-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0019_camp_bp_camp_bp_commentaire_camp_bp_etat_camp_gi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='BP_deadline',
            field=models.CharField(blank=True, default='30 Janvier', max_length=50, null=True, verbose_name='Date limite du BP'),
        ),
        migrations.AddField(
            model_name='camp',
            name='GI_deadline',
            field=models.CharField(blank=True, default='30 Janvier', max_length=50, null=True, verbose_name='Date limite du GI'),
        ),
        migrations.AddField(
            model_name='camp',
            name='PPP_deadline',
            field=models.CharField(blank=True, default='30 Janvier', max_length=50, null=True, verbose_name='Date limite du PPP'),
        ),
        migrations.AddField(
            model_name='camp',
            name='PPPc_deadline',
            field=models.CharField(blank=True, default='30 Janvier', max_length=50, null=True, verbose_name='Date limite du PPPc'),
        ),
        migrations.AddField(
            model_name='camp',
            name='PPTPV_deadline',
            field=models.CharField(blank=True, default='30 Janvier', max_length=50, null=True, verbose_name='Date limite du PPTPV'),
        ),
        migrations.AddField(
            model_name='camp',
            name='V1GC_deadline',
            field=models.CharField(blank=True, default='30 Janvier', max_length=50, null=True, verbose_name='Date limite du V1GC'),
        ),
        migrations.AddField(
            model_name='camp',
            name='V2GC_deadline',
            field=models.CharField(blank=True, default='30 Janvier', max_length=50, null=True, verbose_name='Date limite du V2GC'),
        ),
        migrations.AddField(
            model_name='camp',
            name='VFGC_deadline',
            field=models.CharField(blank=True, default='30 Janvier', max_length=50, null=True, verbose_name='Date limite du VFGC'),
        ),
        migrations.AddField(
            model_name='camp',
            name='casting_deadline',
            field=models.CharField(blank=True, default='30 Janvier', max_length=50, null=True, verbose_name='Date limite du Casting'),
        ),
        migrations.AddField(
            model_name='camp',
            name='devisbillet_deadline',
            field=models.CharField(blank=True, default='30 Janvier', max_length=50, null=True, verbose_name='Date limite du devisbillet'),
        ),
        migrations.AddField(
            model_name='camp',
            name='devislogement_deadline',
            field=models.CharField(blank=True, default='30 Janvier', max_length=50, null=True, verbose_name='Date limite du devislogement'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='BP',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/bp/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='GI',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/gi/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='GI_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du GI'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='PPP',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/ppp/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='PPP_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du PPP'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='PPPc',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/pppc/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='PPPc_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du PPPc'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='PPTPV',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/pptpv/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='PPTPV_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du PPTPV'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='V1GC',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/v1gc/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='V1GC_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du V1GC'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='V2GC',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/v2gc/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='V2GC_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du V2GC'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='VFGC',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/vfgc/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='VFGC_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du VFGC'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='casting',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/casting/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='casting_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du Casting'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='devisbillet',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/devisbillet/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='devisbillet_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du devisbillet'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='devislogement',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/devislogement/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='devislogement_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait')], default='Non rendu', max_length=50, null=True, verbose_name='État du devislogement'),
        ),
    ]
