# Generated by Django 4.2.16 on 2025-02-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0020_camp_bp_deadline_camp_gi_deadline_camp_ppp_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='PAF_deadline',
            field=models.CharField(blank=True, default='30 Janvier', max_length=50, null=True, verbose_name='Date limite de la PAF'),
        ),
        migrations.AddField(
            model_name='camp',
            name='PAF_etat',
            field=models.CharField(blank=True, choices=[('Uploadé', 'Uploadé'), ('En cours', 'En cours'), ('Pas Uploadé', 'Pa Uploadé')], default='Non rendu', max_length=50, null=True, verbose_name='État de la PAF'),
        ),
    ]
