# Generated by Django 5.1.6 on 2025-02-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0022_alter_camp_bp_etat_alter_camp_budget_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='grille_ddcs_deadline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Date limite de la grille DDCS'),
        ),
    ]
