# Generated by Django 5.1.6 on 2025-02-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0023_alter_camp_grille_ddcs_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='grille_camp_deadline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Date limite de la grille camp'),
        ),
    ]
