# Generated by Django 5.1.6 on 2025-02-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0024_alter_camp_grille_camp_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='projetv1',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/projetv1/depot'),
        ),
        migrations.AddField(
            model_name='camp',
            name='projetv1_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='projetv1_deadline',
            field=models.CharField(blank=True, default='18 mars', max_length=50, null=True, verbose_name='Date limite demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='projetv1_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État de la demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='projetv1_retour',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/projetv1/retour'),
        ),
    ]
