# Generated by Django 5.1.6 on 2025-02-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0025_camp_projetv1_camp_projetv1_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='grille_intendance_deadline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Date limite de la grille intendance'),
        ),
    ]
