# Generated by Django 5.1.6 on 2025-02-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0027_alter_camp_fiche_sncf_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='intendance2',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/intendance2/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='intendance2_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de la grille intendance'),
        ),
        migrations.AddField(
            model_name='camp',
            name='intendance2_deadline',
            field=models.CharField(blank=True, default='15 avril', max_length=50, null=True, verbose_name='Date limite de la grille intendance'),
        ),
        migrations.AddField(
            model_name='camp',
            name='intendance2_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État de la grille intendance'),
        ),
    ]
