# Generated by Django 5.1.6 on 2025-02-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0028_camp_intendance2_camp_intendance2_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='grille_assurance_deadline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Date limite de la grille d'assurance"),
        ),
    ]
