# Generated by Django 5.1.6 on 2025-02-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0029_alter_camp_grille_assurance_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='fil_bleu_retour',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/fil_bleu/retour/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='fil_rouge_retour',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/fil_rouge/retour/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='fil_vert_retour',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/fil_vert/retour/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='fil_bleu',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/fil_bleu/depot/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='fil_bleu_deadline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Date limite du fil rouge'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='fil_rouge',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/fil_rouge/depot/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='fil_rouge_deadline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Date limite du fil rouge'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='fil_vert',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/fil_vert/depot/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='fil_vert_deadline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Date limite du fil rouge'),
        ),
    ]
