# Generated by Django 5.1.6 on 2025-02-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0030_camp_fil_bleu_retour_camp_fil_rouge_retour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='Budget_deadline',
            field=models.CharField(blank=True, default='Debut mai', max_length=50, null=True, verbose_name='Date limite du budget'),
        ),
    ]
