# Generated by Django 5.1.6 on 2025-02-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0032_camp_budgereal_etat_camp_budgetreal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='voiture',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/voiture/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='voiture_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire du budget'),
        ),
        migrations.AddField(
            model_name='camp',
            name='voiture_deadline',
            field=models.CharField(blank=True, default='Debut mai', max_length=50, null=True, verbose_name='Date limite du budget'),
        ),
        migrations.AddField(
            model_name='camp',
            name='voiture_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État du budget'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='Budgetreal_deadline',
            field=models.CharField(blank=True, default='11 mai', max_length=50, null=True, verbose_name='Date limite du budget'),
        ),
    ]
