# Generated by Django 5.1.6 on 2025-02-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0033_camp_voiture_camp_voiture_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='projetvf',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/projetvf/depot'),
        ),
        migrations.AddField(
            model_name='camp',
            name='projetvf_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='projetvf_deadline',
            field=models.CharField(blank=True, default='2 semaines après les JN', max_length=50, null=True, verbose_name='Date limite demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='projetvf_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État de la demande de prospe'),
        ),
        migrations.AddField(
            model_name='camp',
            name='projetvf_retour',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/projetvf/retour'),
        ),
    ]
