# Generated by Django 5.1.6 on 2025-02-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0035_camp_docacm_deadline_camp_docacm_prospe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp',
            old_name='Budgereal_etat',
            new_name='Budgetreal_etat',
        ),
        migrations.AlterField(
            model_name='camp',
            name='projetv1',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/projetv1/depot/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='projetv1_retour',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/projetv1/retour/'),
        ),
    ]
