# Generated by Django 5.1.6 on 2025-02-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0037_camp_jn_camp_jn_commentaire_camp_jn_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp',
            old_name='docACM_prospe',
            new_name='docACM',
        ),
        migrations.RenameField(
            model_name='camp',
            old_name='docACM_prospe_commentaire',
            new_name='docACM_commentaire',
        ),
        migrations.RenameField(
            model_name='camp',
            old_name='docACM_prospe_etat',
            new_name='docACM_etat',
        ),
    ]
