# Generated by Django 5.1.6 on 2025-02-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0038_rename_docacm_prospe_camp_docacm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='drive',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lien du drive'),
        ),
    ]
