# Generated by Django 5.1.6 on 2025-03-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0039_camp_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='drive',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Lien du drive'),
        ),
    ]
