# Generated by Django 5.2.6 on 2025-09-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0040_alter_camp_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lienbc',
            field=models.URLField(blank=True, help_text='Lien vers la page BC', max_length=500, null=True, verbose_name='Lien BC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lienbm',
            field=models.URLField(blank=True, help_text='Lien vers la page BM', max_length=500, null=True, verbose_name='Lien BM'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lienlog',
            field=models.URLField(blank=True, help_text='Lien vers la page logistique', max_length=500, null=True, verbose_name='Lien logistique'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='drive',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lien du drive'),
        ),
    ]
