# Generated by Django 5.2.6 on 2025-09-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0041_customuser_lienbc_customuser_lienbm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commentaireddcs',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire de la grille DDCS'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='commentairefbbc',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire du fil bleu BC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='commentairefbbm',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire du fil bleu BM'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='commentairefrbc',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire du fil rouge BC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='commentairefrbm',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire du fil rouge BM'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='commentairegrille',
            field=models.TextField(blank=True, default='', null=True, verbose_name="Commentaire de la grille de l'annee"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='etatddcs',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État de la grille DDCS'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='etatfbbc',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État du fil bleu BC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='etatfbbm',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État du fil bleu BM'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='etatfrbc',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État du fil rouge BC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='etatfrbm',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État du fil rouge BM'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='etatgrille',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name="État de la grille de l'annee"),
        ),
        migrations.AlterField(
            model_name='camp',
            name='GL1',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Bar Cokhba', 'Bar Cokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrénoy', 'Dufrénoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-Bois', 'Pavillons-sous-Bois'), ('Saint Brice', 'Saint Brice'), ('Ségur', 'Ségur'), ('Shema Israël Bleu', 'Shema Israël Bleu'), ('Shema Israël Noir', 'Shema Israël Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona'), ('NML', 'NML'), ('Dor Vador', 'Dor Vador'), ('Edmond Fleg', 'Edmond Fleg'), ('Neuilly Laurent Kern', 'Neuilly Laurent Kern')], max_length=30, null=True, verbose_name='Groupe local 1'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='GL2',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Bar Cokhba', 'Bar Cokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrénoy', 'Dufrénoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-Bois', 'Pavillons-sous-Bois'), ('Saint Brice', 'Saint Brice'), ('Ségur', 'Ségur'), ('Shema Israël Bleu', 'Shema Israël Bleu'), ('Shema Israël Noir', 'Shema Israël Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona'), ('NML', 'NML'), ('Dor Vador', 'Dor Vador'), ('Edmond Fleg', 'Edmond Fleg'), ('Neuilly Laurent Kern', 'Neuilly Laurent Kern')], max_length=30, null=True, verbose_name='Groupe local 2'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='GL3',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Bar Cokhba', 'Bar Cokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrénoy', 'Dufrénoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-Bois', 'Pavillons-sous-Bois'), ('Saint Brice', 'Saint Brice'), ('Ségur', 'Ségur'), ('Shema Israël Bleu', 'Shema Israël Bleu'), ('Shema Israël Noir', 'Shema Israël Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona'), ('NML', 'NML'), ('Dor Vador', 'Dor Vador'), ('Edmond Fleg', 'Edmond Fleg'), ('Neuilly Laurent Kern', 'Neuilly Laurent Kern')], max_length=30, null=True, verbose_name='Groupe local 3'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='GL4',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Bar Cokhba', 'Bar Cokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrénoy', 'Dufrénoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-Bois', 'Pavillons-sous-Bois'), ('Saint Brice', 'Saint Brice'), ('Ségur', 'Ségur'), ('Shema Israël Bleu', 'Shema Israël Bleu'), ('Shema Israël Noir', 'Shema Israël Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona'), ('NML', 'NML'), ('Dor Vador', 'Dor Vador'), ('Edmond Fleg', 'Edmond Fleg'), ('Neuilly Laurent Kern', 'Neuilly Laurent Kern')], max_length=30, null=True, verbose_name='Groupe local 4'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='GL5',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Bar Cokhba', 'Bar Cokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrénoy', 'Dufrénoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-Bois', 'Pavillons-sous-Bois'), ('Saint Brice', 'Saint Brice'), ('Ségur', 'Ségur'), ('Shema Israël Bleu', 'Shema Israël Bleu'), ('Shema Israël Noir', 'Shema Israël Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona'), ('NML', 'NML'), ('Dor Vador', 'Dor Vador'), ('Edmond Fleg', 'Edmond Fleg'), ('Neuilly Laurent Kern', 'Neuilly Laurent Kern')], max_length=30, null=True, verbose_name='Groupe local 5'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gl',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Bar Cokhba', 'Bar Cokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrénoy', 'Dufrénoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-Bois', 'Pavillons-sous-Bois'), ('Saint Brice', 'Saint Brice'), ('Ségur', 'Ségur'), ('Shema Israël Bleu', 'Shema Israël Bleu'), ('Shema Israël Noir', 'Shema Israël Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona'), ('NML', 'NML'), ('Dor Vador', 'Dor Vador'), ('Edmond Fleg', 'Edmond Fleg'), ('Neuilly Laurent Kern', 'Neuilly Laurent Kern')], max_length=30, null=True, verbose_name='Groupe local'),
        ),
    ]
