# Generated by Django 5.2.6 on 2025-09-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0042_customuser_commentaireddcs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commentaireprojetactivitebc',
            field=models.TextField(blank=True, default='', null=True, verbose_name="Commentaire de l'ébauche projet d'activité BC"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='commentaireprojetviejuvebc',
            field=models.TextField(blank=True, default='', null=True, verbose_name="Commentaire de l'ébauche projet vie juive BC"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='etatprojetactivitebc',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name="État de l'ébauche projet d'activité BC"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='etatprojetviejuvebc',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name="État de l'ébauche projet vie juive BC"),
        ),
        migrations.AlterField(
            model_name='camp',
            name='GL1',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Barcokhba', 'Barcokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrenoy', 'Dufrenoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-bois', 'Pavillons-sous-bois'), ('Saint-Brice', 'Saint-Brice'), ('Ségur', 'Ségur'), ('Shema Israel Bleu', 'Shema Israel Bleu'), ('Shema Israel Noir', 'Shema Israel Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona'), ('NML', 'NML'), ('Dor Vador', 'Dor Vador'), ('Edmond Fleg', 'Edmond Fleg'), ('Neuilly Laurent Kern', 'Neuilly Laurent Kern')], max_length=30, null=True, verbose_name='Groupe local 1'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='GL2',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Barcokhba', 'Barcokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrenoy', 'Dufrenoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-bois', 'Pavillons-sous-bois'), ('Saint-Brice', 'Saint-Brice'), ('Ségur', 'Ségur'), ('Shema Israel Bleu', 'Shema Israel Bleu'), ('Shema Israel Noir', 'Shema Israel Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona'), ('NML', 'NML'), ('Dor Vador', 'Dor Vador'), ('Edmond Fleg', 'Edmond Fleg'), ('Neuilly Laurent Kern', 'Neuilly Laurent Kern')], max_length=30, null=True, verbose_name='Groupe local 2'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='GL3',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Barcokhba', 'Barcokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrenoy', 'Dufrenoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-bois', 'Pavillons-sous-bois'), ('Saint-Brice', 'Saint-Brice'), ('Ségur', 'Ségur'), ('Shema Israel Bleu', 'Shema Israel Bleu'), ('Shema Israel Noir', 'Shema Israel Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona'), ('NML', 'NML'), ('Dor Vador', 'Dor Vador'), ('Edmond Fleg', 'Edmond Fleg'), ('Neuilly Laurent Kern', 'Neuilly Laurent Kern')], max_length=30, null=True, verbose_name='Groupe local 3'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='GL4',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Barcokhba', 'Barcokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrenoy', 'Dufrenoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-bois', 'Pavillons-sous-bois'), ('Saint-Brice', 'Saint-Brice'), ('Ségur', 'Ségur'), ('Shema Israel Bleu', 'Shema Israel Bleu'), ('Shema Israel Noir', 'Shema Israel Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona'), ('NML', 'NML'), ('Dor Vador', 'Dor Vador'), ('Edmond Fleg', 'Edmond Fleg'), ('Neuilly Laurent Kern', 'Neuilly Laurent Kern')], max_length=30, null=True, verbose_name='Groupe local 4'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='GL5',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Barcokhba', 'Barcokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrenoy', 'Dufrenoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-bois', 'Pavillons-sous-bois'), ('Saint-Brice', 'Saint-Brice'), ('Ségur', 'Ségur'), ('Shema Israel Bleu', 'Shema Israel Bleu'), ('Shema Israel Noir', 'Shema Israel Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona'), ('NML', 'NML'), ('Dor Vador', 'Dor Vador'), ('Edmond Fleg', 'Edmond Fleg'), ('Neuilly Laurent Kern', 'Neuilly Laurent Kern')], max_length=30, null=True, verbose_name='Groupe local 5'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gl',
            field=models.CharField(blank=True, choices=[('Aix-en-Provence', 'Aix-en-Provence'), ('Antony', 'Antony'), ('Barcokhba', 'Barcokhba'), ('Bordeaux', 'Bordeaux'), ('Buffault', 'Buffault'), ('Canada', 'Canada'), ('Cannes', 'Cannes'), ('Colmar-Mulhouse', 'Colmar-Mulhouse'), ('Copernic', 'Copernic'), ('Courbevoie', 'Courbevoie'), ('Dufrenoy', 'Dufrenoy'), ('Golda Meir', 'Golda Meir'), ('Grenoble', 'Grenoble'), ('Henri Schilli', 'Henri Schilli'), ('Israël', 'Israël'), ('Issy-les-Moulineaux', 'Issy-les-Moulineaux'), ('Koumi SLG', 'Koumi SLG'), ('La Victoire', 'La Victoire'), ('Paris 12', 'Paris 12'), ('Lille', 'Lille'), ('Londres', 'Londres'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Montpellier', 'Montpellier'), ('Nancy-Metz-Luxembourg', 'Nancy-Metz-Luxembourg'), ('Neuilly Vert', 'Neuilly Vert'), ('Neuilly Rose', 'Neuilly Rose'), ('Nice', 'Nice'), ('Noam', 'Noam'), ('Ori SLG', 'Ori SLG'), ('La Roquette', 'La Roquette'), ('Paris 17', 'Paris 17'), ('Pavillons-sous-bois', 'Pavillons-sous-bois'), ('Saint-Brice', 'Saint-Brice'), ('Ségur', 'Ségur'), ('Shema Israel Bleu', 'Shema Israel Bleu'), ('Shema Israel Noir', 'Shema Israel Noir'), ('Strasbourg', 'Strasbourg'), ('Toulon', 'Toulon'), ('Toulouse', 'Toulouse'), ('Versailles', 'Versailles'), ('Yona', 'Yona'), ('NML', 'NML'), ('Dor Vador', 'Dor Vador'), ('Edmond Fleg', 'Edmond Fleg'), ('Neuilly Laurent Kern', 'Neuilly Laurent Kern')], max_length=30, null=True, verbose_name='Groupe local'),
        ),
    ]
