# Generated by Django 5.2.6 on 2026-02-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0043_customuser_commentaireprojetactivitebc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='Budget_RDV',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='Budget RDV'),
        ),
        migrations.AddField(
            model_name='camp',
            name='Budget_RDV_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='Budget_RDV_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite budget RDV'),
        ),
        migrations.AddField(
            model_name='camp',
            name='Budget_RDV_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État du budget RDV'),
        ),
        migrations.AddField(
            model_name='camp',
            name='JN_2026',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/jn_2026/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='JN_2026_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='JN_2026_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite JN 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='JN_2026_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État du JN 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='assurance_2026',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/assurance_2026/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='assurance_2026_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='assurance_2026_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite assurance 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='assurance_2026_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name="État de l'assurance 2026"),
        ),
        migrations.AddField(
            model_name='camp',
            name='billets_2026',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/billets_2026/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='billets_2026_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='billets_2026_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite billets 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='billets_2026_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État des billets 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='budget_2026',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/budget_2026/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='budget_2026_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='budget_2026_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite budget 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='budget_2026_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État du budget 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='commandes_intendance_2026',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/commandes_intendance_2026/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='commandes_intendance_2026_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='commandes_intendance_2026_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite commandes intendance 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='commandes_intendance_2026_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État de la commandes intendance 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_camp_2026',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/grille_camp_2026/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_camp_2026_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_camp_2026_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite grille camp 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_camp_2026_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État de la grille camp 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_intendance_2026',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/grille_intendance_2026/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_intendance_2026_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_intendance_2026_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite grille intendance 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='grille_intendance_2026_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État de la grille intendance 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='inscriptions_prio',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='Inscriptions prioritaires'),
        ),
        migrations.AddField(
            model_name='camp',
            name='inscriptions_prio_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='inscriptions_prio_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite inscriptions prioritaires'),
        ),
        migrations.AddField(
            model_name='camp',
            name='inscriptions_prio_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État des inscriptions prioritaires'),
        ),
        migrations.AddField(
            model_name='camp',
            name='maitrise_2026',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/maitrise_2026/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='maitrise_2026_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='maitrise_2026_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite maitrise 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='maitrise_2026_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État de la maitrise 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pav2',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/pav2/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pav2_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pav2_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite PAV2'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pav2_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État du PAV2'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pavf',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/pavf/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pavf_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pavf_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite PAVF'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pavf_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État du PAVF'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pppv1',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/pppv1/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pppv1_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pppv1_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite PPPv1'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pppv1_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État du PPPv1'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pvcv2',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/pvcv2/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pvcv2_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pvcv2_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite PVCv2'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pvcv2_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État du PVCv2'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pvcvf',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/pvcvf/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pvcvf_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pvcvf_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite PVCVF'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pvcvf_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État du PVCVF'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pvjv2',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/pvjv2/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pvjv2_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pvjv2_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite PVJV2'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pvjv2_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État du PVJV2'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pvjvf',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/pvjvf/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pvjvf_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pvjvf_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite PVJVF'),
        ),
        migrations.AddField(
            model_name='camp',
            name='pvjvf_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État du PVJVF'),
        ),
        migrations.AddField(
            model_name='camp',
            name='sncf_2026',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/sncf_2026/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='sncf_2026_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='sncf_2026_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite sncf 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='sncf_2026_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État de la sncf 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='voiture_2026',
            field=models.FileField(blank=True, null=True, upload_to='media/fichiers_camps/voiture_2026/'),
        ),
        migrations.AddField(
            model_name='camp',
            name='voiture_2026_commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='camp',
            name='voiture_2026_deadline',
            field=models.CharField(blank=True, default='10 Fevrier', max_length=50, null=True, verbose_name='Date limite voiture 2026'),
        ),
        migrations.AddField(
            model_name='camp',
            name='voiture_2026_etat',
            field=models.CharField(blank=True, choices=[('Rendu', 'Rendu'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Non rendu', 'Non rendu'), ('Retour fait', 'Retour fait'), ('En cours', 'En cours')], default='Non rendu', max_length=50, null=True, verbose_name='État de la voiture 2026'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='numero',
            field=models.CharField(blank=True, choices=[('BB 1', 'BB 1'), ('BB 2', 'BB 2'), ('BB 3', 'BB 3'), ('BB 4', 'BB 4'), ('BB 5', 'BB 5'), ('BC 1', 'BC 1'), ('BC 2', 'BC 2'), ('BC 3', 'BC 3'), ('BC 4', 'BC 4'), ('BC 5', 'BC 5'), ('BC 6', 'BC 6'), ('BC 7', 'BC 7'), ('BC 8', 'BC 8'), ('BC 9', 'BC 9'), ('BC 10', 'BC 10'), ('BC 11', 'BC 11'), ('BC 12', 'BC 12'), ('BC 13', 'BC 13'), ('BC 14', 'BC 14'), ('BC 15', 'BC 15'), ('BC 16', 'BC 16'), ('BC 17', 'BC 17'), ('BC 18', 'BC 18'), ('BM 1', 'BM 1'), ('BM 2', 'BM 2'), ('BM 3', 'BM 3'), ('BM 4', 'BM 4'), ('BM 5', 'BM 5'), ('BM 6', 'BM 6'), ('BM 7', 'BM 7'), ('BM 8', 'BM 8'), ('BM 9', 'BM 9'), ('BM 10', 'BM 10'), ('BM 11', 'BM 11'), ('BM 12', 'BM 12'), ('BM 13', 'BM 13'), ('BM 14', 'BM 14'), ('BM 15', 'BM 15'), ('BM 16', 'BM 16'), ('BM 17', 'BM 17'), ('BM 18', 'BM 18'), ('BM 19', 'BM 19'), ('BM 20', 'BM 20'), ('BM 21', 'BM 21'), ('BM 22', 'BM 22'), ('BM 23', 'BM 23'), ('BM 24', 'BM 24'), ('BM 25', 'BM 25'), ('BP 1', 'BP 1'), ('BP 2', 'BP 2'), ('BP 3', 'BP 3'), ('BP 4', 'BP 4'), ('BP 5', 'BP 5'), ('BP 6', 'BP 6'), ('BP 7', 'BP 7'), ('BP 8', 'BP 8'), ('BP 9', 'BP 9'), ('BP 10', 'BP 10'), ('BP 11', 'BP 11')], max_length=30, null=True, unique=True, verbose_name='Numéro du camp'),
        ),
    ]
