# Generated by Django 5.2.6 on 2026-02-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0044_camp_budget_rdv_camp_budget_rdv_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='Budget_RDV_deadline',
            field=models.CharField(blank=True, default='23 au 29 mars', max_length=50, null=True, verbose_name='Date limite budget RDV'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='JN_2026_deadline',
            field=models.CharField(blank=True, default='Dates JN : mi avril', max_length=50, null=True, verbose_name='Date limite JN 2026'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='assurance_2026_deadline',
            field=models.CharField(blank=True, default='15 avril', max_length=50, null=True, verbose_name='Date limite assurance 2026'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='billets_2026_deadline',
            field=models.CharField(blank=True, default='Pas de deadline', max_length=50, null=True, verbose_name='Date limite billets 2026'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='budget_2026_deadline',
            field=models.CharField(blank=True, default='16 mars', max_length=50, null=True, verbose_name='Date limite budget 2026'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='commandes_intendance_2026_deadline',
            field=models.CharField(blank=True, default='27 avril', max_length=50, null=True, verbose_name='Date limite commandes intendance 2026'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='grille_camp_2026_deadline',
            field=models.CharField(blank=True, default='9 mars', max_length=50, null=True, verbose_name='Date limite grille camp 2026'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='grille_intendance_2026_deadline',
            field=models.CharField(blank=True, default='23 mars', max_length=50, null=True, verbose_name='Date limite grille intendance 2026'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='inscriptions_prio_deadline',
            field=models.CharField(blank=True, default='10 février', max_length=50, null=True, verbose_name='Date limite inscriptions prioritaires'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='maitrise_2026_deadline',
            field=models.CharField(blank=True, default='5 avril', max_length=50, null=True, verbose_name='Date limite maitrise 2026'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='pav2_deadline',
            field=models.CharField(blank=True, default='2 semaines après les JN', max_length=50, null=True, verbose_name='Date limite PAV2'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='pavf_deadline',
            field=models.CharField(blank=True, default='A définir', max_length=50, null=True, verbose_name='Date limite PAVF'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='pppv1_deadline',
            field=models.CharField(blank=True, default='2 semaines avant les JN', max_length=50, null=True, verbose_name='Date limite PPPv1'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='pvcv2_deadline',
            field=models.CharField(blank=True, default='2 semaines après les JN', max_length=50, null=True, verbose_name='Date limite PVCv2'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='pvcvf_deadline',
            field=models.CharField(blank=True, default='A définir', max_length=50, null=True, verbose_name='Date limite PVCVF'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='pvjv2_deadline',
            field=models.CharField(blank=True, default='2 semaines après les JN', max_length=50, null=True, verbose_name='Date limite PVJV2'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='pvjvf_deadline',
            field=models.CharField(blank=True, default='A définir', max_length=50, null=True, verbose_name='Date limite PVJVF'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='sncf_2026_deadline',
            field=models.CharField(blank=True, default='Dès que le contrat est signé', max_length=50, null=True, verbose_name='Date limite sncf 2026'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='voiture_2026_deadline',
            field=models.CharField(blank=True, default='18 mai', max_length=50, null=True, verbose_name='Date limite voiture 2026'),
        ),
    ]
