# Generated by Django 5.2.6 on 2026-02-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0045_alter_camp_budget_rdv_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='CR_prospe_deadline',
            field=models.CharField(blank=True, default='28 février', max_length=50, null=True, verbose_name='Date limite du CR prospection'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='contrat_location_deadline',
            field=models.CharField(blank=True, default='28 février', max_length=50, null=True, verbose_name='Date limite du contrat de location'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='demande_prospe_deadline',
            field=models.CharField(blank=True, default='28 février', max_length=50, null=True, verbose_name='Date limite demande de prospe'),
        ),
    ]
