# Generated by Django 5.2.6 on 2026-02-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0046_alter_camp_cr_prospe_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='billets_2026_deadline',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Date limite billets 2026'),
        ),
    ]
