# Generated by Django 5.2.6 on 2026-02-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0047_alter_camp_billets_2026_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='JN_2026_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de JN choisie'),
        ),
    ]
