# Generated by Django 5.2.6 on 2026-02-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0048_camp_jn_2026_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='JN_2026_deadline',
            field=models.CharField(blank=True, default='mi-avril', max_length=50, null=True, verbose_name='Date limite JN 2026'),
        ),
    ]
