# Generated by Django 4.2.30 on 2026-05-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0050_alter_camp_gl1_alter_camp_gl2_alter_camp_gl3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='commandes_intendance_2026_deadline',
            field=models.CharField(blank=True, default='4 mai', max_length=50, null=True, verbose_name='Date limite commandes intendance 2026'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='grille_intendance_2026_deadline',
            field=models.CharField(blank=True, default='24 avril', max_length=50, null=True, verbose_name='Date limite grille intendance 2026'),
        ),
    ]
